server:
  port: 9002

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Ls6WyHuxYiWHBYscrLYB
            client-secret: eezxJFpaU2
            scope:
              - name
              - nickname
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http:/localhost:9002/oauth/naver/callback
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

jwt:
  issuer: dlstlr1707@gmail.com
  secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==

oauth:
  naver:
    client-id: Ls6WyHuxYiWHBYscrLYB
    client-secret: eezxJFpaU2
    redirect-uri: http://localhost:9002/oauth/naver/callback
    state: 1234
  kakao:
    client-id: 9e4af8cd72b29e0dea144d556907435e
    redirect-uri: http://localhost:9002/oauth/kakao/callback