name: Jacoco Test Coverage Check

# 1단계
on:
  pull_request:
    types: [opened, synchronize, reopened]

# 2단계
permissions: write-all

# 3단계
jobs:
  test:
    runs-on: ubuntu-latest
	
    steps:
      # 3-1단계
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

	# 3-2단계
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          
      # 3-4단계
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3-6단계
      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          title: Test Coverage Report
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
